site_name: RoboLoco Docs
site_url: https://roboloco.org/
site_description: RoboLoCo Documentation
site_author: David Macpherson

repo_url: https://github.com/ironon/RoboLoco-Docs




theme:
  name: null
  custom_dir: 'custom_theme/'
  logo: '/assets/img/roboloco.png'
  static_templates:
  - 404.html
  locale: en

  include_search_page: true
  search_index_only: false

  highlightjs: true
  hljs_languages: []

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - callouts

plugins:
  - search
  - gen-files:
      scripts:
        - gen_pages.py  # or any other name or path'
watch:
- custom_theme

nav:
- "Home": index.md
- "Daily Progress": Progress.md
- "Software": software.md
- "Mechanical": mechanical.md
- "Creative": creative.md
- "Business": business.md
